// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: fluxcache.proto

package grpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_fluxcache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_fluxcache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_fluxcache_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Command) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type ResponseValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Str           string                 `protobuf:"bytes,2,opt,name=str,proto3" json:"str,omitempty"`
	Num           int64                  `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	Bulk          string                 `protobuf:"bytes,4,opt,name=bulk,proto3" json:"bulk,omitempty"`
	Array         []*ResponseValue       `protobuf:"bytes,5,rep,name=array,proto3" json:"array,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseValue) Reset() {
	*x = ResponseValue{}
	mi := &file_fluxcache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseValue) ProtoMessage() {}

func (x *ResponseValue) ProtoReflect() protoreflect.Message {
	mi := &file_fluxcache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseValue.ProtoReflect.Descriptor instead.
func (*ResponseValue) Descriptor() ([]byte, []int) {
	return file_fluxcache_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseValue) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResponseValue) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

func (x *ResponseValue) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *ResponseValue) GetBulk() string {
	if x != nil {
		return x.Bulk
	}
	return ""
}

func (x *ResponseValue) GetArray() []*ResponseValue {
	if x != nil {
		return x.Array
	}
	return nil
}

var File_fluxcache_proto protoreflect.FileDescriptor

const file_fluxcache_proto_rawDesc = "" +
	"\n" +
	"\x0ffluxcache.proto\x12\tfluxcache\"1\n" +
	"\aCommand\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"\x8b\x01\n" +
	"\rResponseValue\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03str\x18\x02 \x01(\tR\x03str\x12\x10\n" +
	"\x03num\x18\x03 \x01(\x03R\x03num\x12\x12\n" +
	"\x04bulk\x18\x04 \x01(\tR\x04bulk\x12.\n" +
	"\x05array\x18\x05 \x03(\v2\x18.fluxcache.ResponseValueR\x05array2A\n" +
	"\tFluxCache\x124\n" +
	"\x04Exec\x12\x12.fluxcache.Command\x1a\x18.fluxcache.ResponseValueB2Z0github.com/FreyreCorona/FluxCache/network/grpcpbb\x06proto3"

var (
	file_fluxcache_proto_rawDescOnce sync.Once
	file_fluxcache_proto_rawDescData []byte
)

func file_fluxcache_proto_rawDescGZIP() []byte {
	file_fluxcache_proto_rawDescOnce.Do(func() {
		file_fluxcache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fluxcache_proto_rawDesc), len(file_fluxcache_proto_rawDesc)))
	})
	return file_fluxcache_proto_rawDescData
}

var file_fluxcache_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fluxcache_proto_goTypes = []any{
	(*Command)(nil),       // 0: fluxcache.Command
	(*ResponseValue)(nil), // 1: fluxcache.ResponseValue
}
var file_fluxcache_proto_depIdxs = []int32{
	1, // 0: fluxcache.ResponseValue.array:type_name -> fluxcache.ResponseValue
	0, // 1: fluxcache.FluxCache.Exec:input_type -> fluxcache.Command
	1, // 2: fluxcache.FluxCache.Exec:output_type -> fluxcache.ResponseValue
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fluxcache_proto_init() }
func file_fluxcache_proto_init() {
	if File_fluxcache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fluxcache_proto_rawDesc), len(file_fluxcache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fluxcache_proto_goTypes,
		DependencyIndexes: file_fluxcache_proto_depIdxs,
		MessageInfos:      file_fluxcache_proto_msgTypes,
	}.Build()
	File_fluxcache_proto = out.File
	file_fluxcache_proto_goTypes = nil
	file_fluxcache_proto_depIdxs = nil
}
