// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: fluxcache.proto

package grpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FluxCache_Exec_FullMethodName = "/fluxcache.FluxCache/Exec"
)

// FluxCacheClient is the client API for FluxCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FluxCacheClient interface {
	Exec(ctx context.Context, in *Command, opts ...grpc.CallOption) (*ResponseValue, error)
}

type fluxCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewFluxCacheClient(cc grpc.ClientConnInterface) FluxCacheClient {
	return &fluxCacheClient{cc}
}

func (c *fluxCacheClient) Exec(ctx context.Context, in *Command, opts ...grpc.CallOption) (*ResponseValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseValue)
	err := c.cc.Invoke(ctx, FluxCache_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FluxCacheServer is the server API for FluxCache service.
// All implementations must embed UnimplementedFluxCacheServer
// for forward compatibility.
type FluxCacheServer interface {
	Exec(context.Context, *Command) (*ResponseValue, error)
	mustEmbedUnimplementedFluxCacheServer()
}

// UnimplementedFluxCacheServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFluxCacheServer struct{}

func (UnimplementedFluxCacheServer) Exec(context.Context, *Command) (*ResponseValue, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedFluxCacheServer) mustEmbedUnimplementedFluxCacheServer() {}
func (UnimplementedFluxCacheServer) testEmbeddedByValue()                   {}

// UnsafeFluxCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FluxCacheServer will
// result in compilation errors.
type UnsafeFluxCacheServer interface {
	mustEmbedUnimplementedFluxCacheServer()
}

func RegisterFluxCacheServer(s grpc.ServiceRegistrar, srv FluxCacheServer) {
	// If the following call panics, it indicates UnimplementedFluxCacheServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FluxCache_ServiceDesc, srv)
}

func _FluxCache_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FluxCacheServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FluxCache_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FluxCacheServer).Exec(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

// FluxCache_ServiceDesc is the grpc.ServiceDesc for FluxCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FluxCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fluxcache.FluxCache",
	HandlerType: (*FluxCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exec",
			Handler:    _FluxCache_Exec_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fluxcache.proto",
}
